export const ADD_SURVEY = 'ADD_SURVEY';
export const GET_ALL_SURVEYS_FROM_USER = 'GET_ALL_SURVEYS_FROM_USER';
export const TOTAL_SURVEYS = 'TOTAL_SURVEYS';
export const UPDATE_SURVEY_STATUS = 'UPDATE_SURVEY_STATUS';