// USER
export const FETCH_USER = 'FETCH_USER';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const EMAIL_CONFIRMATION_MESSAGE = 'EMAIL_CONFIRMATION_MESSAGE';

// BILLING
export const ADD_CREDITS = 'ADD_CREDITS';
export const UPDATE_CREDITS = 'UPDATE_CREDITS';
export const FETCH_CREDITS = 'FETCH_CREDITS';

// NAVIGATION
export const TOGGLE_MENU_STATE = 'TOGGLE_MENU_STATE';

